version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/github_action
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    onwer: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/gh_bdeploy.sh
      timeout: 60
      runas: ubuntu